---
- name: "Check for squid executable file"
  ansible.builtin.stat:
    path: '/usr/sbin/squid'
  changed_when: false
  register: squid_binary

- name: "Install tasks"
  when: not squid_binary.stat.exists
  block:
    - name: "Install squid package"
      ansible.builtin.package:
        name: "squid"
        state: present
        update_cache: true

    - name: "Creating log directory"
      ansible.builtin.file:
        path: "/var/log/squid/"
        state: directory
        mode: '0755'

    - name: "Change ulimit for root"
      community.general.pam_limits:
        domain: root
        limit_type: '-'
        limit_item: nofile
        value: "{{ squid_max_filedescriptors }}"

    - name: "Change ulimit for all"
      community.general.pam_limits:
        domain: '*'
        limit_type: '-'
        limit_item: nofile
        value: "{{ squid_max_filedescriptors }}"

- name: "Configure squid.conf"
  ansible.builtin.template:
    src: "squid.conf.j2"
    dest: "/etc/squid/squid.conf"
    mode: '0644'
  notify:
    - "Test squid configuration"
    - "Restart squid"

- name: "Start and enable squid"
  ansible.builtin.service:
    name: squid
    state: started
    enabled: true
